### ISSUE TITLE
[WemadeCodzState] Final Project

### ISSUE THREAD

**Issue by kjh24871** [codestates/WBABEProject-01#1]
### ISSUE
-Group: `Client`, `Server`, `Sr`
-Type: `bug`, `feature`, `delete`
-Detail: fix actions from client dedux

* * *
### TODO
* 문서
    - [ ] README 작성
    - [x] Issue Templete 작성
    - [x] Milestone 작성

 * * *
 ###API 설계
* 피주문자
    - [x] [메뉴 신규 등록  - 피주문자]
    - [x] [메뉴 수정 / 삭제 - 피주문자]
    - [ ] [주문 상태 조회 - 피주문자]

* 주문자
    - [x] [메뉴 리스트 출력 조회 - 주문자]
    - [x] [메뉴별 평점 및 리뷰 조회 - 주문자]
    - [x] [메뉴별 평점 작성 - 주문자]
    - [ ] [주문 - 주문자]
    - [ ] [주문 변경 - 주문자]
    - [ ] [주문 내역 조회 - 주문자]

**Comment by Hooneats** [comment]
안녕하세요. 프로젝트 연결이잘못된것같아요.(제가 이름을 너무 헷갈리게 만들었나봐요) 이게 프로젝트 관리기능이다보니 각 프로젝트별로 있어야할것같은데 일단 이건 제가 만든거다보니 헷갈릴수도 있어서 권한쪽 설정 변경해서 막을게요!
