### ISSUE TITLE
[WemadeCodzState] DB & Menu API

### ISSUE THREAD

**Issue by kjh24871** [codestates/WBABEProject-01#2]
### ISSUE
-Group: `Client`, `Server`, `Sr`
-Type: `bug`, `feature`, `delete`
-Detail: fix actions from client dedux

* * *
### TODO
* DB
    - [x] DB엔티티 설정
    - [x] DB테이블 작성
* 피주문자
    - [x] [메뉴 신규 등록  - 피주문자]
    - [x] [메뉴 수정 / 삭제 - 피주문자]
    - [x] [주문 상태 조회 - 피주문자]
