### ISSUE TITLE
[WemadeCodzState] Order API

### ISSUE THREAD

**Issue by kjh24871** [codestates/WBABEProject-01#4]
### ISSUE
-Group: `Client`, `Server`, `Sr`
-Type: `bug`, `feature`, `delete`
-Detail: fix actions from client dedux

* * *
### TODO

* 피주문자
    - [x] [주문 상태 조회 - 피주문자]

* 주문자
    - [x] [주문 - 주문자]
    - [x] [주문 추가 - 주문자]
    - [x] [주문 내역 조회 - 주문자]
